const TASKMANAGER_CONSTANTS = {};
TASKMANAGER_CONSTANTS.ASK = "ASK";
TASKMANAGER_CONSTANTS.CANCEL = "CANCEL";
TASKMANAGER_CONSTANTS.FORCE = "FORCE";
TASKMANAGER_CONSTANTS.CLOSE_REFERENCE = "close";
TASKMANAGER_CONSTANTS.REMOVE_REFERENCE = "remove";

export default TASKMANAGER_CONSTANTS