import '../../test-page/test-page'

import './backup.spec'
import './end_groups.spec'
import './hidden.spec'
import './select_group.spec'
import './selector.spec'
import './session.spec'
import './storage.spec'
import './switch_group.spec'
import './tabmanager.spec'
import './tabs_add_remove.spec'
import './window_manager.spec'