import '../../test-page/test-page'

import './background.spec'
import './comparator.spec'
import './corrupted.spec'
import './filestorage.spec'
import './groupmanager.spec'
import './logmanager.spec'
import './search.spec'
import './session.spec'
import './taskmanager.spec'